name: Deploy Laravel to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Execute SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home2/harishanjra/public_html/git
            git pull origin main
            /usr/local/bin/ea-php82 /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
            /usr/local/bin/ea-php82 artisan migrate --force
            /usr/local/bin/ea-php82 artisan config:cache
            /usr/local/bin/ea-php82 artisan route:cache
            /usr/local/bin/ea-php82 artisan view:cache
